name: publish_conda

on:
   push
jobs:
#   build:
#     strategy:
#       matrix:
#         python: ['3.9']
#         os: ['windows-2016','ubuntu-latest']
#     runs-on: ${{ matrix.os }}     
#     steps:
#     - uses: actions/checkout@v2
#     - name: submodules
# #       shell: bash -l {0}
#       run: |
#         git submodule update --init --recursive
#     - name: Add msbuild to PATH
#       if: matrix.os == 'windows-2016'
#       uses: microsoft/setup-msbuild@v1.0.2
#     - uses: conda-incubator/setup-miniconda@v2
#       with:
#         python-version: ${{ matrix.python }} 
#         activate-environment: loop    
#     - name: Conda build'
#       env:
#         ANACONDA_API_TOKEN: ${{ secrets.ANACONDA }}
# #       shell: powershell
#       run: |
#         conda install -c conda-forge conda-build scikit-build numpy=1.20 cython anaconda-client -y
#         conda build -c anaconda -c conda-forge -c loop3d --output-folder conda conda
#         conda install anaconda-client -y
#         anaconda upload --label main conda/win-64/*.tar.bz2 
#   upload:
#       runs-on: ubuntu-latest
#       steps:
#       - name: install anaconda
#         uses: conda-incubator/setup-miniconda@v2
#         with:
#            python-version: 3.8
#            activate-environment: loop
#       - name: upload
#         run: |
#          conda install -y anaconda-client
#          anaconda 
# jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "2.7"]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: install conda libs
        shell: bash -l {0}
        run: conda install -c conda-forge conda-build scikit-build numpy=1.20 cython anaconda-client -y
      - name: Conda list
        shell: pwsh
        run: conda list
     
