name: publish_conda

on:
   push
jobs:
  conda-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: loop3d/publish_to_conda@0.1
        with:
           token: ${{ secrets.ANACONDA }}
#     name: Uploading to Loop3d for python ${{ matrix.os }})
#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: false
#       matrix:
#         os: ["ubuntu-latest",  "windows-latest"] #"macos-latest",
#         python-version: ["3.7"]
#     steps:
#       - uses: conda-incubator/setup-miniconda@v2
#         with:
#           auto-update-conda: true
#           python-version: ${{ matrix.python-version }}
    
#       - uses: actions/checkout@v2
#       - name: update submodules
# #       shell: bash -l {0}
#         run: |
#             git submodule update --init --recursive
#       - name: Add msbuild to PATH
#         if: matrix.os == 'windows-2016'
#         uses: microsoft/setup-msbuild@v1.0.2  
#       - name: Conda build'
#         env:
#           ANACONDA_API_TOKEN: ${{ secrets.ANACONDA }}
#         shell: bash -l {0}
#         run: |
#            conda install -c conda-forge conda-build scikit-build numpy=1.20 cython anaconda-client -y
#            conda build -c anaconda -c conda-forge -c loop3d --output-folder conda conda
#            conda install anaconda-client -y
#       - name: upload windows
#         env:
#           ANACONDA_API_TOKEN: ${{ secrets.ANACONDA }}
#         if: matrix.os == 'windows-latest'
#         shell: bash -l {0}
#         run: |
#            anaconda upload --label main conda/win-64/*.tar.bz2 
#       - name: upload linux
#         env:
#           ANACONDA_API_TOKEN: ${{ secrets.ANACONDA }}
#         if: matrix.os == 'ubuntu-latest'
#         shell: bash -l {0}
#         run: |
#            anaconda upload --label main conda/linux-64/*.tar.bz2 
#       - name: upload macosx
#         env:
#           ANACONDA_API_TOKEN: ${{ secrets.ANACONDA }}
#         if: matrix.os == 'macos-latest'
#         shell: bash -l {0}
#         run: |
#             anaconda upload --label main conda/osx-64/*.tar.bz2

    
    
# #       - uses: conda-incubator/setup-miniconda@v2
# #         with:
# #           auto-update-conda: true
# #           python-version: ${{ matrix.python-version }}
# #       - name: Conda info
# #         shell: bash -l {0}
# #         run: conda info
# #       - name: install conda libs
# #         shell: bash -l {0}
# #         run: conda install -c conda-forge conda-build scikit-build numpy=1.20 cython anaconda-client -y
# #       - name: Conda list
# #         shell: pwsh
# #         run: conda list
# #       - name: run anaconda
# #         shell: bash -l {0}
# #         run: anaconda 
     
