on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release

        with:
          release-type: python
          package-name: python_template
          draft: True
  
  documentation:
    runs-on: ubuntu-latest
    needs: release-please
#     if: 
    steps:
      - run: echo ${{ needs.release.outputs.release_created }}
