on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release

        with:
          release-type: python
          package-name: python_template
          draft: True
      - name: test 
        run: echo "hello"
        if:  ${{ steps.release.outputs.release_created }}
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
  documentation:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - run: echo "results are ${{ needs.release-please.outputs.release_created }}"
